### ISSUE TITLE
第一次启动：type mismatch

### ISSUE THREAD

**Issue by JaryZhen** [MadeInChina/play2-oauth2-example#1]
type mismatch;
 found   : play.api.libs.iteratee.Iteratee[Array[Byte],Either[play.api.mvc.Results.Status,T]]
 required: play.api.libs.streams.Accumulator[akka.util.ByteString,Either[play.api.mvc.Result,?]]

![image](https://user-images.githubusercontent.com/13216107/39391728-cfc315ca-4ada-11e8-8704-be74db26b0d8.png)

**Comment by hanrw** [comment]
@JaryZhen 从新Pull下试试看

**Comment by hanrw** [comment]
@JaryZhen branch play-2.6.13 with latest version.
